language: cpp
compiler: clang

# Travis by default uses Clang version 3.4, which is to old for us (no c++14).
addons:
    apt:
        sources:
            - llvm-toolchain-precise-3.7
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.7
            - g++-5
            - gcc-5
            - binutils
            - llvm-3.7-dev
            - libclang-common-3.7-dev
            - libunittest++-dev
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi

script: make SHELL="/bin/sh -x"
